### ISSUE TITLE
Developing a strict typed version

### ISSUE THREAD

**Issue by Mistralys** [pear/HTML_Common2#2]
FYI, I am working on a strict typed version of the class for PHP >= 7.4, which fully uses type hints. I use HTML_Common2 in a number of legacy projects, which are slowly migrating to strict typing. 

My first idea was to publish a strict typed version in a separate package on Github. However, I would be happy to contribute to a new HTML_Common3 project or something similar that would officially tie into the PEAR projects. Do you have any thoughts or preferences regarding this?

**Comment by golgote** [comment]
Hi Sebastian, I think HTML_Common3 would be the best way to go. This way you can also modify the API if you want to.

**Comment by Mistralys** [comment]
Thanks for the feedback!
