### ISSUE TITLE
PHP 8.1: Deprecation notice at htmlspecialchars

### ISSUE THREAD

**Issue by alexgit2k** [pear/HTML_Common2#4]
If an attribute-value is `null` then PHP 8.1 will print a deprecation notice for htmlspecialchars:
https://github.com/pear/HTML_Common2/blob/3d7f6956ff1b479847b227194c23eb0d5d053a9e/HTML/Common2.php#L263

### Example
```
docker run -it --rm php:8.1 /bin/bash

apt-get update -yqq && apt-get install -y git
curl https://getcomposer.org/download/latest-stable/composer.phar > /usr/local/bin/composer
chmod a+rx /usr/local/bin/composer
composer require pear/html_common2

cat <<EOT > test.php
<?php
require_once('vendor/autoload.php');

class foobar extends HTML_Common2 {
  public function __toString() { return ''; }
  public function set(\$key, \$value) { \$this->attributes[\$key]=\$value; }
}

\$common = new foobar();
\$common->set('test',null);
var_dump(\$common->getAttributes(true));
EOT

php test.php
```

### Output
```
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /vendor/pear/html_common2/HTML/Common2.php on line 263
string(8) " test="""
```

**Comment by sad-spirit** [comment]
Issue looks bogus to me. There is a public `setAttribute()` method that is also mapped to `offsetSet()` and it does not allow adding non-string values to `$attributes` property. Use that.

**Comment by alexgit2k** [comment]
This was just a small example to force the deprecation notice. It's a real-word-problem, we get this in our application. So please reopen it @sad-spirit.

**Comment by sad-spirit** [comment]
> It's a real-word-problem, we get this in our application.

@alexgit2k --- can you please show how to trigger this problem using the _public_ API?
